# Generated by Django 5.2.13 on 2026-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_set1', '0009_anoud_make_model_mapping'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='anoudmakemodelmapping',
            new_name='api_set1_an_bayanat_361c0c_idx',
            old_name='api_set1_an_bayana_e90d28_idx',
        ),
    ]
